env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "cirrus-ci.org"
    rom_name: Nusantara
    device: lavender
    
task:
  name: "Snx-R"
  # skip: $CIRRUS_BRANCH == 'main'
  timeout_in: 4h
  container:
      image: snaxpsycho/cirrus:latest
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
      volumes:
          - /home/cirrus:/home/cirrus
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
        
  notify_script:
    - set -e
    - bash <(curl -s https://raw.githubusercontent.com/$CIRRUS_REPO_FULL_NAME/$CIRRUS_BRANCH/snx/notify.sh)
 
   notify0_script:
    - set -e
    - rm -rf ~/.bin/repo
    - curl https://android.googlesource.com/tools/repo/+/refs/tags/v2.36.1/repo > ~/.bin/repo
    - chmod a+rx ~/.bin/repo
    
  notify1_script:
    - set -e
    - repo init --depth=1 --no-repo-verify -u https://Sa-Sajjad:$ght@github.com/S-A-build/android_manifest_nusa.git -b battery -g default,-mips,-darwin,-notdefault
    
  notify2_script:
    - set -e
    - git clone git@github.com:Sa-Sajjad/manifest.git --depth 1 -b hmp2 .repo/local_manifests
  
  notify3_script:
    - set -e
    - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
    
  # sync_script:
    # - set -e
    # - bash <(curl -s https://raw.githubusercontent.com/$CIRRUS_REPO_FULL_NAME/$CIRRUS_BRANCH/snx/sync.sh)

  vanilla_build_script:
    - bash <(curl -s https://raw.githubusercontent.com/$CIRRUS_REPO_FULL_NAME/$CIRRUS_BRANCH/snx/build.sh)
    
  apps_up_script:
    - set -e
    - bash <(curl -s https://raw.githubusercontent.com/$CIRRUS_REPO_FULL_NAME/$CIRRUS_BRANCH/snx/upload_apps.sh)
    
  # gapps_build_script:
    # - set -e
    # - bash <(curl -s https://raw.githubusercontent.com/$CIRRUS_REPO_FULL_NAME/$CIRRUS_BRANCH/snx/gapps_build.sh)
    
  # gapps_up_script:
    # - set -e
    # - bash <(curl -s https://raw.githubusercontent.com/$CIRRUS_REPO_FULL_NAME/$CIRRUS_BRANCH/snx/sfg_uploader.sh)
