env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "cirrus-ci.org"
    rom_name: Nusantara
    device: lavender
    
task:
  name: "Snx-R"
  timeout_in: 4h
  container:
      image: snaxpsycho/snaxpsycho:test
      cpu: 2
      memory: 4G
      stateful: true
      greedy: true
      volumes:
          - /home/cirrus:/home/cirrus
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
    
  notify_script:
    - wget https://sa.mirror-hub.workers.dev/0:/snx/AncientOS-R-Weeabo-v5.7-lavender-Rias_Gremory-20220107-1900-Vanilla.zip
    - file=*.zip
    - dlink=$(basename *.zip)
    - rsync -vhcP -e ssh $file sa-sajjad@frs.sourceforge.net:/home/frs/project/snx/lavender/
    - echo "Download link https://sourceforge.net/projects/snx/files/lavender/$dlink/download"
    
    
  # notify_script:
    # - set -e
    # - bash <(curl -s https://raw.githubusercontent.com/My-builder/My-builder/$CIRRUS_BRANCH/snx/notify.sh)
    
  # tsync_script:
    # - set -e
    # - bash <(curl -s https://raw.githubusercontent.com/My-builder/My-builder/$CIRRUS_BRANCH/snx/tsync.sh)
    
  # sync_script:
    # - set -e
    # - bash <(curl -s https://raw.githubusercontent.com/My-builder/My-builder/$CIRRUS_BRANCH/snx/sync.sh)    

  # build_script:
    # - bash <(curl -s https://raw.githubusercontent.com/My-builder/My-builder/$CIRRUS_BRANCH/snx/build.sh)        

  # ccache_stats_script:
    # - set -e
    # - export CCACHE_DIR=~/ccache/$rom_name/$device
    # - ccache -s
  
  # apps_up_script:
    # - bash <(curl -s https://raw.githubusercontent.com/My-builder/My-builder/$CIRRUS_BRANCH/snx/uploading_apps.sh)    
        
  # upload_script:
    # - bash <(curl -s https://raw.githubusercontent.com/My-builder/My-builder/$CIRRUS_BRANCH/snx/sfg_uploader.sh)    
    
  # remove_script:
    # - set -e
    # - cd ~/$rom_name
    # - rm -rf out/target/product/$device
    